### PR TITLE
Delete debug_api.rs

### LINKED ISSUE #367: [Refactor] Remove the debug api in the runtime crate.
## Enhancement

Because APIs located in `kclvm/runtime/src/stdlib/debug_api.rs` are no longer in use, we can delete them and the functions they use.

### PR DESCRIPTION
**Pull request by Rishav1707**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #367", "re #367".):

- [ ] N
- [x] Y 

#### 2. What is the scope of this PR (e.g. component or file name):

`kclvm/runtime/src/stdlib/debug_api.rs`

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [x] Other
- `debud_api.rs` file is no longer needed.

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y

### CODE REVIEW

**Comment by Rishav1707** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Peefy** [comment]
Hi, @Rishav1707. Welcome to KCLVM! Thanks for your contribution! Maybe you forgot to deal with the related function calls in `debug_api.rs`, please delete them to ensure that the KCLVM rust project compilation passes.

**Comment by Rishav1707** [comment]
> Hi, @Rishav1707. Welcome to KCLVM! Thanks for your contribution! Maybe you forgot to deal with the related function calls in `debug_api.rs`, please delete them to ensure that the KCLVM rust project compilation passes.

But, I have already deleted all the related function calls.

**Comment by Peefy** [comment]
> > Hi, @Rishav1707. Welcome to KCLVM! Thanks for your contribution! Maybe you forgot to deal with the related function calls in `debug_api.rs`, please delete them to ensure that the KCLVM rust project compilation passes.
> 
> But, I have already deleted all the related function calls.

For example, https://github.com/KusionStack/KCLVM/compare/main...Peefy:KCLVM:remove-debug-api?expand=1, If you delete this file, you also need to delete the corresponding module declaration in `mod.rs`.

**Comment by Rishav1707** [comment]
> > > Hi, @Rishav1707. Welcome to KCLVM! Thanks for your contribution! Maybe you forgot to deal with the related function calls in `debug_api.rs`, please delete them to ensure that the KCLVM rust project compilation passes.
> > 
> > 
> > But, I have already deleted all the related function calls.
> 
> For example, https://github.com/KusionStack/KCLVM/compare/main...Peefy:KCLVM:remove-debug-api?expand=1, If you delete this file, you also need to delete the corresponding module declaration in `mod.rs`.

Thank you for your help😊

**Review by Peefy — APPROVED** [review]
LGTM

**Review by zong-zhe — APPROVED** [review]
LGTM

**Pull request merged**
