### PR TITLE
refactor: replace json_minimal with serde_json

### LINKED ISSUE #201: [Bug] `json.decode` raise an strange error when input invalid json string
`json.decode` raise an strange error when input invalid json string

## Case 1

KCL code:

```kcl
import json

data = json.decode("{") # when input an invalid json string
```

I got

```
KCL Runtime Error[E3M38] : Evaluation failure
---> File test.k:3
3 |data = json.decode("{") # when input an invalid json string -> Failure
decode() missing 1 required positional argument: 'value'
```

Expected:

```
KCL Runtime Error[E3M38] : Evaluation failure
---> File /Users/lingzhi/_Code/Python/Konfig/a.k:3
3 |data = json.decode("{") # when input an invalid json string -> Failure
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

## Case 2

KCL code:

```kcl
import json

data = json.decode("\n{}") # when input an invalid json string
```

I got

```
KCL Runtime Error[E3M38] : Evaluation failure
---> File test.k:3
3 |data = json.decode("\n{}") # when input an invalid json string -> Failure
decode() missing 1 required positional argument: 'value'
```

Expected:

```yaml
data: {}
```

Related files:

* kclvm/runtime/src/value/val_json.rs
* kclvm/runtime/src/json/json.rs

KCLVM version:

*  0.4.3

### PR DESCRIPTION
**Pull request by NeverRaR**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 
re #201 

#### 2. What is the scope of this PR (e.g. component or file name):

kclvm/runtime/src/3rdparty/json_minimal
kclvm/runtime/src/json/json.rs
#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other
replace json_minimal with serde_json to fix #201 

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

test cases in kclvm/runtime/src/value/val_json.rs: `test_value_from_err_json()` is used to test decode invalid json

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Peefy** [comment]
Pls add more test cases for `val_json.rs` including all functions and cases in #201

**Review by Peefy — DISMISSED** [review]
LGTM

**Review by Peefy — APPROVED** [review]
LGTM

**Review by zong-zhe — APPROVED** [review]
LGTM

**Pull request merged**
