### PR TITLE
Feat(compiler-base): add error message.

### PR DESCRIPTION
**Pull request by zong-zhe**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

issue #115

#### 2. What is the scope of this PR (e.g. component or file name):

compiler_base/error_message.rs

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [x] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

add `ErrorMessage` to define the message displayed in diagnostics.
add `TemplateLoader` to load text template file ("*.ftl").

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [x] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

add unit test in compiler_base/tests.rs

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by zong-zhe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Peefy** [comment]
Three important things:
1. It is recommended to use `anyhow::Result` as a function return instead of `.unwrap_or_else(|| bug!("xx"));` Because it's not actually an internal compiler error but some user errors.
2. Whether it is a high-level or medium-level API, try to keep the interface as simple as possible, such as importing only one file and using one structure.
3. Try the `once_cell` crate to init `TempateMessageLoader`.

**Review by Peefy — COMMENTED** [review]
Three important things:

It is recommended to use anyhow::Result as a function return instead of .unwrap_or_else(|| bug!("xx")); Because it's not actually an internal compiler error but some user errors.
Whether it is a high-level or medium-level API, try to keep the interface as simple as possible, such as importing only one file and using one structure.
Try the once_cell crate to init TempateMessageLoader.Three important things:

It is recommended to use anyhow::Result as a function return instead of .unwrap_or_else(|| bug!("xx")); Because it's not actually an internal compiler error but some user errors.
Whether it is a high-level or medium-level API, try to keep the interface as simple as possible, such as importing only one file and using one structure.
Try the once_cell crate to init TempateMessageLoader.

**Review by Peefy — APPROVED** [review]
LGTM

**Review by ldxdl — APPROVED** [review]
LGM

**Pull request merged**
